### PR TITLE
Add redis log/state support; chronicle config

### PR DESCRIPTION
**Pull request by nick-cromwell**
# Info
This Pull Request is related to issue no. [6, 24]

# Changes
- Add Redis SagaLog and SagaStateResporitories.
- Add ``Type MessageType`` to SagaLog to deserialize to correct message type.
- Rename various 'Id' and 'Type' to more descriptive 'SagaId' and 'SagaType'.
- Make several constructors public and add [JsonConstructor] attributes.
- Add ChronicleConfig with default implementation added to service collection.
- Add DeleteOnCompleted() builder method.
- Add DeleteAsync to ISagaLog and ISagaStateRespository interfaces.
- Initial unit tests - to be expanded on.

### CODE REVIEW

**Comment by paolofulgoni** [comment]
I think that Redis persistence should be implemented in a different package (e.g. `Chronicle_.Redis`) along with it's dependencies (i.e. `Microsoft.Extensions.Caching.Redis`)

**Comment by nick-cromwell** [comment]
@paolofulgoni I agree. I'll refactor it into a separate package in the next day or two

**Comment by nick-cromwell** [comment]
@paolofulgoni Actually before committing too much to refactoring I'd like get @GooRiOn 's input. I'll wait for his initial feedback

**Comment by paolofulgoni** [comment]
It may be a different project altogether, see [Chronicle.Integrations.MongoDB](https://github.com/chronicle-stack/Chronicle.Integrations.MongoDB).

**Comment by nick-cromwell** [comment]
@paolofulgoni Oh nice, I hadn't seen that repo. That'll be much better. @GooRiOn, if you could create a Chronicle.Integrations.Redis repo I will refactor most of this and push changes to there in a couple days. I'll cherry pick some of these commits and when all is done make a new PR for this repo too.

**Comment by GooRiOn** [comment]
I created a dedicated repo for you :)

https://github.com/chronicle-stack/Chronicle.Integrations.Redis

**Pull request closed without merging**
